---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(gghighlight)
```

```{r}
df <- readr::read_rds("data/data-jpm.Rds")
```


```{r}
glimpse(df)
```

```{r}
df %>% 
  ggplot(aes(id, change, group = category, color = category)) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_line() +
  geom_point() +
  gghighlight(
    change[which(id == 15)] < -50   # filter(id == 15, change < -50)
  ) +
  theme_bw() +
  rcartocolor::scale_colour_carto_d() #+
  # facet_wrap(~ category)
```

```{r}
plot1 <- df %>% 
  ggplot(aes(id, change, group = category, color = category)) +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 11, linetype = "dashed", color = "grey") +
  geom_line() +
  geom_point(size = 1) +
  gghighlight(
    change[which(id == 15)] < -50
  ) +
  # gghighlight(change < - 50) +
  theme_bw() +
  rcartocolor::scale_colour_carto_d() +
  facet_wrap(~ category)
plot1
```
The above is good, but the `geom_vline` and `geom_hline` functions fake out the `facet_wrap` function.  Solve this by first building the basic plot, then use `gghighlight`, then `facet_wrap`, then add back the v and h.  This problem is progressively solved below.

```{r}
plot1
```
```{r fig.height=7, fig.width=10}
gg <-
  ggplot(df, aes(id, change, color = category)) +
    geom_point() +
    geom_line(size = .8, alpha = .5) +
    gghighlight::gghighlight(
      use_direct_label = F,
      unhighlighted_params = list(color = "grey70", size = .5)
    ) +
    facet_wrap(~ category, ncol = 4, scales = "free_x") +
    coord_cartesian(clip = "off") +
    scale_x_continuous(
      expand = c(.003, .003),
      breaks = seq(1, 15, by = 2),
      labels = c("Jan 4", "Jan 18", "Feb 1", "Feb 15", "Feb 29", "Mar 14", "Mar 28", "Apr 11")
    ) +
    scale_y_continuous(
      breaks = seq(-80, 60, by = 20),
      labels = glue::glue("{seq(-80, 60, by = 20)}%")
    ) +
    scale_color_viridis_d(option = "inferno", end = .8, begin = .1, guide = "none") +
    labs(
      x = "End of week", y = NULL,
      title = "Year-over-year percent change in spending by essential category",
      caption = "Source: JPMorgan Chase Institute | Makeover: Cedric Scherer, Frontpage Data"
    )

gg
```

```{r fig.height=10, fig.width=10}
gg + 
  geom_vline(xintercept = 10.85, color = "grey40", linetype = "dashed") +
  geom_hline(yintercept = 0, color = "grey30", size = .8) +
  geom_area(alpha = .1) +
  geom_line(size = 1.2) +
  geom_point(size = 1.8) +
  geom_text(
    data = tibble(
      id = 10.6,
      change = -60,
      label = "National emergency\ndeclared March 13",
      category = factor("Groceries", levels = levels(df$category)) 
    ),
    aes(label = label),
    color = "grey40",
    lineheight = .95,
    hjust = 1
  )
```

Deconstructing Cedric's code, I have simplified some elements, for my clarifying benefit.  

```{r fig.height=10, fig.width=10}
df %>% 
  ggplot(aes(id, change, group = category, color = category)) +
  # geom_hline(yintercept = 0, color = "grey") +
  geom_line() +
  geom_point() +
  gghighlight(
      use_direct_label = FALSE,
      unhighlighted_params = list(color = "grey80", size = .5)) +
  # theme_bw() +
  # rcartocolor::scale_colour_carto_d() +
  scale_color_viridis_d(guide = FALSE) +
  # scale_color_brewer(guide = FALSE) +
  facet_wrap(~ category) +
  geom_vline(xintercept = 10.85, color = "grey40", linetype = "dashed") +
  geom_hline(yintercept = 0, color = "grey30", size = .8) +
  geom_area(alpha = .3) +
  geom_line(size = 1.2) +
  geom_point(size = 1.8) +
  geom_text(
    data = tibble(
      id = 8.6,
      change = -60,
      label = "ipsum lipsum\ncranberry6\nMarch 13",
      category = factor("Auto Repair", levels = levels(df$category)) 
    ),
    aes(label = label),
    color = "grey40",
    lineheight = .95,
    hjust = 1
  )
  



```

```{r}
df %>% 
  ggplot(aes(id, change, group = category, color = category)) +
  geom_line() +
  geom_point(size = 1) +
  geom_hline(yintercept = 0, color = "grey40") +
  geom_vline(xintercept = 10, color = "grey40", linetype = "dashed") +
  geom_area(data = . %>% filter(category == "Groceries"), alpha = .3) +
  gghighlight(category == "Groceries",
      use_direct_label = TRUE,
      unhighlighted_params = list(color = "grey70", size = .5)) +
  guides(color = FALSE)
```

